# Generated by Django 5.1.1 on 2024-11-04 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_rename_product_recipes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipes',
            new_name='Recipe',
        ),
    ]
